# Docker Compose for Flutter Web (Nginx)
services:
  web:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./build/web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
